spring:
  application:
    name: boardProject
  datasource:
    url: jdbc:postgresql://svc.sel5.cloudtype.app:32599/friend
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

server:
  port: 9900